spring:
  application:
    name: POST-SERVICE

  config:
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      profile: local

server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true

