spring:
  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      profile: local

server:
  port: 9002
grpc:
  server:
    port: 9092